apiVersion: v1
kind: Service
metadata:
  name: ticket-booking-service
  labels:
    app: ticket-booking-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: ticket-booking-app
